### ISSUE TITLE
Fix Travis ARM builds

### ISSUE THREAD

**Issue by reliveyy** [ExchangeUnion/xud-docker-bot#9] opened 2020-08-17 21:30 UTC
The Travis ARM builds failed a lot due to 10m no output error.

**Comment by kilrau** [comment] 2020-08-17 22:52
Duplicate of https://github.com/ExchangeUnion/xud-docker/issues/598 ?

**Comment by reliveyy** [comment] 2020-08-18 08:55
> Duplicate of [ExchangeUnion/xud-docker#598](https://github.com/ExchangeUnion/xud-docker/issues/598) ?

Yep. Since there isn't any .travis.yml in xud-docker project, it's better to track this issue on bot side.

**Comment by kilrau** [comment] 2020-08-18 13:02
Ok, closed ExchangeUnion/xud-docker#598

**Comment by reliveyy** [comment] 2020-08-27 14:06
The above fix is not working. One failed Travis build raw log

```
travis_fold:start:worker_info
[0K[33;1mWorker information[0m
hostname: 0cfc9a82-044a-4229-bf4a-2bb5a307e8e8@85186.lxd-arm64-04-org
version: ? ?
instance: travis-job-exchangeunion-xud-docker-721633710 041de6436b01c6903beca15dc30bac68973e0910a594214e3b8d7922c5ec5a3c (via amqp)
startup: 18.298086211s
travis_fold:end:worker_info
[0Ktravis_time:start:186946d3
[0Ktravis_time:end:186946d3:start=1598521471569919508,finish=1598521472093253021,duration=523333513,event=no_world_writable_dirs
[0Ktravis_time:start:2e1f4978
[0Ktravis_time:end:2e1f4978:start=1598521472114307301,finish=1598521472136878592,duration=22571291,event=setup_filter
[0Ktravis_time:start:0552a668
[0Ktravis_time:end:0552a668:start=1598521472145333939,finish=1598521472191639111,duration=46305172,event=agent
[0Ktravis_time:start:12174f14
[0Ktravis_time:end:12174f14:start=1598521472200989275,finish=1598521472214059004,duration=13069729,event=check_unsupported
[0Ktravis_time:start:062829f0
[0Ktravis_fold:start:system_info
[0K[33;1mBuild system information[0m
Build language: python
Build dist: bionic
Build id: 721633708
Job id: 721633710
Runtime kernel version: 5.3.0-42-generic
travis-build version: 035b5ff6
[34m[1mBuild image provisioning date and time[0m
Sat Jul 11 08:51:14 UTC 2020
[34m[1mOperating System Details[0m
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
[34m[1mLinux Version[0m
5.0.0-23-generic
[34m[1mGit version[0m
git version 2.17.1
[34m[1mbash version[0m
GNU bash, version 4.4.20(1)-release (aarch64-unknown-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
[34m[1mGCC version[0m
gcc (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[34m[1mDocker version[0m
Client:
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        369ce74a3c
 Built:             Fri Feb 28 23:47:53 2020
 OS/Arch:           linux/arm64
 Experimental:      false
[34m[1mLLVM version[0m
clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
[34m[1mPre-installed Ruby versions[0m
ruby-2.6.3
ruby-2.6.5
ruby-2.7.0
[34m[1mPre-installed Node.js versions[0m
v10.21.0
v12.18.2
v4.9.1
v6.17.1
v8.12.0
v8.17.0
[34m[1mmysql --version[0m
mysql  Ver 14.14 Distrib 5.7.30, for Linux (aarch64) using  EditLine wrapper
[34m[1mRedis version[0m
redis-server 5.0.6
[34m[1mMongoDB version[0m
MongoDB 4.2.8
[34m[1mkiex list[0m

kiex elixirs

=* elixir-1.9.1

# => - current
# =* - current && default
#  * - default

[34m[1mphpenv versions[0m
  7.2
  7.2.32
* 7.3 (set by /home/travis/.phpenv/version)
  7.3.20
  7.4
  7.4.8
[34m[1mcomposer --version[0m
Composer version 1.10.8 2020-06-24 21:23:30
travis_fold:end:system_info
[0K
travis_time:end:062829f0:start=1598521472234232093,finish=1598521472259427135,duration=25195042,event=show_system_info
[0Ktravis_time:start:0d407198
[0Ktravis_time:end:0d407198:start=1598521472267084814,finish=1598521472320434546,duration=53349732,event=rm_riak_source
[0Ktravis_time:start:04dc063a
[0Ktravis_time:end:04dc063a:start=1598521472335147610,finish=1598521472378024639,duration=42877029,event=fix_rwky_redis
[0Ktravis_time:start:0c42a31b
[0Ktravis_time:end:0c42a31b:start=1598521472390453974,finish=1598521473123936545,duration=733482571,event=wait_for_network
[0Ktravis_time:start:0195a0a6
[0Ktravis_time:end:0195a0a6:start=1598521473138456460,finish=1598521474028950806,duration=890494346,event=update_apt_keys
[0Ktravis_time:start:032db5b1
[0Ktravis_time:end:032db5b1:start=1598521474048815123,finish=1598521474270349651,duration=221534528,event=fix_hhvm_source
[0Ktravis_time:start:03683ad2
[0Ktravis_time:end:03683ad2:start=1598521474277492235,finish=1598521474322400095,duration=44907860,event=update_mongo_arch
[0Ktravis_time:start:02970d9e
[0Ktravis_time:end:02970d9e:start=1598521474346309424,finish=1598521474511430948,duration=165121524,event=fix_sudo_enabled_trusty
[0Ktravis_time:start:06e43789
[0Ktravis_time:end:06e43789:start=1598521474541380071,finish=1598521474555380442,duration=14000371,event=update_glibc
[0Ktravis_time:start:054b15fd
[0Ktravis_time:end:054b15fd:start=1598521474576300524,finish=1598521474620730713,duration=44430189,event=clean_up_path
[0Ktravis_time:start:0aeb8fde
[0Ktravis_time:end:0aeb8fde:start=1598521474643924824,finish=1598521474655903638,duration=11978814,event=fix_mvn_settings_xml
[0Ktravis_time:start:21f961c2
[0Ktravis_time:end:21f961c2:start=1598521474684237401,finish=1598521474744219197,duration=59981796,event=no_ipv6_localhost
[0Ktravis_time:start:1ec9dea5
[0Ktravis_time:end:1ec9dea5:start=1598521474764831932,finish=1598521474786424207,duration=21592275,event=fix_etc_mavenrc
[0Ktravis_time:start:18931ea4
[0Ktravis_time:end:18931ea4:start=1598521474807478663,finish=1598521474830917021,duration=23438358,event=fix_wwdr_certificate
[0Ktravis_time:start:1641751e
[0Ktravis_time:end:1641751e:start=1598521474852642695,finish=1598521474983036241,duration=130393546,event=put_localhost_first
[0Ktravis_time:start:03f58d70
[0Ktravis_time:end:03f58d70:start=1598521475004380318,finish=1598521475015963936,duration=11583618,event=home_paths
[0Ktravis_time:start:17f49905
[0Ktravis_time:end:17f49905:start=1598521475030456027,finish=1598521475105824881,duration=75368854,event=disable_initramfs
[0Ktravis_time:start:20a46980
[0Ktravis_time:end:20a46980:start=1598521475127125759,finish=1598521475202607662,duration=75481903,event=disable_ssh_roaming
[0Ktravis_time:start:07b13af0
[0Ktravis_time:end:07b13af0:start=1598521475216117512,finish=1598521475227808279,duration=11690767,event=debug_tools
[0Ktravis_time:start:00e11f81
[0Ktravis_time:end:00e11f81:start=1598521475241910224,finish=1598521475253748340,duration=11838116,event=uninstall_oclint
[0Ktravis_time:start:00485385
[0Ktravis_time:end:00485385:start=1598521475265570630,finish=1598521475272425967,duration=6855337,event=rvm_use
[0Ktravis_time:start:1ecf4620
[0Ktravis_time:end:1ecf4620:start=1598521475292975352,finish=1598521475326813690,duration=33838338,event=rm_etc_boto_cfg
[0Ktravis_time:start:0e9640a6
[0Ktravis_time:end:0e9640a6:start=1598521475348112943,finish=1598521475369912966,duration=21800023,event=rm_oraclejdk8_symlink
[0Ktravis_time:start:040dae04
[0Ktravis_time:end:040dae04:start=1598521475392257210,finish=1598521475416601510,duration=24344300,event=enable_i386
[0Ktravis_time:start:0fcc4785
[0Ktravis_time:end:0fcc4785:start=1598521475439790396,finish=1598521475468120484,duration=28330088,event=update_rubygems
[0Ktravis_time:start:1f068378
[0Ktravis_time:end:1f068378:start=1598521475491024423,finish=1598521475524009393,duration=32984970,event=ensure_path_components
[0Ktravis_time:start:1a710c63
[0Ktravis_time:end:1a710c63:start=1598521475538467334,finish=1598521475544457779,duration=5990445,event=redefine_curl
[0Ktravis_time:start:0dcbdc2c
[0Ktravis_time:end:0dcbdc2c:start=1598521475560002160,finish=1598521475646287763,duration=86285603,event=nonblock_pipe
[0Ktravis_time:start:18812148
[0Ktravis_time:end:18812148:start=1598521475653732369,finish=1598521481816848012,duration=6163115643,event=apt_get_update
[0Ktravis_time:start:0780d1e0
[0Ktravis_time:end:0780d1e0:start=1598521481839373604,finish=1598521481846710411,duration=7336807,event=deprecate_xcode_64
[0Ktravis_time:start:2ed4c24b
[0Ktravis_time:end:2ed4c24b:start=1598521481862658939,finish=1598521481875775343,duration=13116404,event=update_heroku
[0Ktravis_time:start:16627bba
[0Ktravis_time:end:16627bba:start=1598521481894338722,finish=1598521481900511940,duration=6173218,event=shell_session_update
[0Ktravis_time:start:13dbef5d
[0Ktravis_fold:start:docker_mtu
[0Ktravis_fold:end:docker_mtu
[0Ktravis_time:end:13dbef5d:start=1598521481915083330,finish=1598521484270055150,duration=2354971820,event=set_docker_mtu
[0Ktravis_time:start:0f435a2c
[0Ktravis_time:end:0f435a2c:start=1598521484281303097,finish=1598521484356940199,duration=75637102,event=resolvconf
[0Ktravis_time:start:06e061f5
[0Ktravis_time:end:06e061f5:start=1598521484378691898,finish=1598521484391013409,duration=12321511,event=maven_central_mirror
[0Ktravis_time:start:096e0502
[0Ktravis_time:end:096e0502:start=1598521484405693249,finish=15985214

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received

The build has been terminated
```

**Comment by reliveyy** [comment] 2020-08-28 09:03
I found the timeout is actually related to `tools/push` command `python helper.py push "$@"`. So I changed `tools/push` for debugging (the following script could prevent ARM 10m error).

```bash
#!/bin/bash

set -m
set -euo pipefail
set -x

function print_running() {
  while true; do
    echo ">>> RUNNING <<<"
    sleep 3
  done
}

print_running &

cd "$(dirname "$0")" || exit 1
python helper.py push "$@"
```

Required commands that will prevent 10m error
1. `set -x`
2. `sleep 3` (60 not working)
3. `print_running &`

Todos:
- [ ] See if I can print_running inside helper.py
- [ ] See why `-x` is required

**Closed as completed** 2020-08-31 08:14 UTC
Labels: bug, P1
